# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - http://link.hhtjim.com/163/425570952.mp3
    - http://link.hhtjim.com/163/425570952.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/IMG_4394.JPG

# 默认文章封面图（随机调用,支持外链）
cover: 
  - http://img.jeson.club:26/2020/03/31/70f811f378e9a.jpg
  - http://img.jeson.club:26/2020/03/31/b108fa8b26529.jpg
  - http://img.jeson.club:26/2020/03/31/7e0f0581d82d5.jpg
  - http://img.jeson.club:26/2020/03/31/5ae8b4b6b35aa.jpg
  - http://img.jeson.club:26/2020/03/31/d8d9df4298036.jpg
  - http://img.jeson.club:26/2020/03/31/feae378bc5b91.jpg
  - http://img.jeson.club:26/2020/03/31/21d19a8464625.jpg
  - http://img.jeson.club:26/2020/03/31/513f9f5d029ad.jpg
  - http://img.jeson.club:26/2020/03/31/f2f935ddf56bf.jpg
  - http://img.jeson.club:26/2020/03/31/350aae6470b2c.jpg
  - http://img.jeson.club:26/2020/03/31/54087529e6108.jpg
  - http://img.jeson.club:26/2020/03/31/69adab8b24a3b.jpg
  - http://img.jeson.club:26/2020/03/31/9a8f2473598c7.jpg
  - http://img.jeson.club:26/2020/03/31/99626e2869f2c.jpg
  - http://img.jeson.club:26/2020/03/31/54f93398c30cf.jpg
  - http://img.jeson.club:26/2020/03/31/271cabf219491.jpg
  - http://img.jeson.club:26/2020/03/31/289a861c2c375.jpg
  - http://img.jeson.club:26/2020/03/31/0143150f9561c.jpg
  - http://img.jeson.club:26/2020/03/31/8af430ab32acf.jpg
  - http://img.jeson.club:26/2020/03/31/90609929ca086.jpg
  - http://img.jeson.club:26/2020/03/31/82dd97ab5fafc.jpg
  - http://img.jeson.club:26/2020/03/31/5a4804631b426.jpg
  - http://img.jeson.club:26/2020/03/31/6f98a9caa482d.jpg
  - http://img.jeson.club:26/2020/03/31/d0f27550f3aff.jpg
  - http://img.jeson.club:26/2020/03/31/e4ba0d0037454.jpg
  - http://img.jeson.club:26/2020/03/31/3fb10dc94e1be.png
  - http://img.jeson.club:26/2020/03/31/9f3a7d40e68a0.png
  - http://img.jeson.club:26/2020/03/31/284ef477c3818.jpg
  - http://img.jeson.club:26/2020/03/31/51b3017f3897b.png
  - http://img.jeson.club:26/2020/03/31/a4461209d56a6.jpg
  - http://img.jeson.club:26/2020/03/31/ab033dd4aa807.jpg
  - http://img.jeson.club:26/2020/03/31/70e460e5f8e26.png

 
# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: /
    twitter: /
    github: https://github.com/jesongit/jesongit.github.io
    wechat: /img/wechat.png
    email: mailto:188380780@qq.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: false
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '9c5dd73f2eb85196a1e3'
    # 应用秘钥
    clientSecret: 'e1edacb8aad39dfd533a58646f134816d501ec3a'
    # issue仓库名
    repo: 'jesongit.github.io'
    # Github名
    owner: 'jesongit'
    # Github名
    admin: ['jesongit']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
